#!/usr/bin/env bash
# Demonstrate every check in tools/validate.py: one refusal and one acceptance.
#
#     bash tests/run-plants.sh [OUT_DIR]
#
# A check that has only been seen failing cannot be distinguished from a check
# that cannot pass, and a check that cannot pass is indistinguishable from one
# that passes everything. Each plant below is generated by tools/make-plants.py
# from real repository data with one cell changed, so a reader can see what the
# defect is and re-run it. OUT_DIR defaults to a directory under the system
# temporary directory and is removed on exit unless it was passed in.
#
# Exits non-zero if a plant that is meant to be refused passes, or if the
# acceptance run of any pass is refused.

set -u

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT" || exit 1

if [ $# -ge 1 ]; then
  OUT="$1"
  CLEAN=0
else
  OUT="$(mktemp -d)"
  CLEAN=1
fi
trap '[ "$CLEAN" = 1 ] && rm -rf "$OUT"' EXIT

PY="${PYTHON:-python3}"
STATUS=0

echo "== regenerating plants under $OUT =="
"$PY" tools/make-plants.py "$OUT/plants" | sed 's/^/   /'
echo

echo "== refusals: each plant must be caught by the check it is named for =="
for plant in "$OUT"/plants/*/; do
  name="$(basename "$plant")"
  for pass_dir in "$plant"*/; do
    [ -d "$pass_dir" ] || continue
    out="$("$PY" tools/validate.py "$pass_dir" 2>&1)"
    code=$?
    expected="$(grep -oP '(?<=- )\[[a-z-]+\]' <<<"$out" | sort -u | tr '\n' ' ')"
    if [ "$code" -eq 0 ]; then
      printf '   FAIL %-22s expected a refusal, the gate exited 0\n' "$name"
      STATUS=1
    else
      printf '   ok   %-22s exit=%s  tripped: %s\n' "$name" "$code" "$expected"
    fi
  done
done
echo

echo "== acceptances: the corrected data must pass =="
for pass_dir in 2026-09-13 2026-09-20 2026-10-02 2026-10-06; do
  out="$("$PY" tools/validate.py "$pass_dir" 2>&1)"
  code=$?
  if [ "$code" -eq 0 ]; then
    printf '   ok   %-12s exit=0\n' "$pass_dir"
  else
    printf '   FAIL %-12s exit=%s\n%s\n' "$pass_dir" "$code" "$out"
    STATUS=1
  fi
done

echo
echo "== whole repository =="
out="$("$PY" tools/validate.py --all 2>&1)"
code=$?
if [ "$code" -eq 0 ]; then
  printf '   ok   validate.py --all exit=0\n'
else
  printf '   FAIL validate.py --all exit=%s\n%s\n' "$code" "$out"
  STATUS=1
fi

exit "$STATUS"