#!/usr/bin/env bash
# Demonstrate every check in tools/validate.py: one refusal and one acceptance.
#
#     bash tests/run-plants.sh [OUT_DIR]
#
# A check that has only been seen failing cannot be distinguished from a check
# that cannot pass, and a check that cannot pass is indistinguishable from one
# that passes everything. Each plant below is generated by tools/make-plants.py
# from real repository data with one cell changed, so a reader can see what the
# defect is and re-run it. The generator writes `manifest.json` naming the check
# each plant must trip, and this harness fails if a plant is caught by anything
# other than that check - a refusal that exits non-zero for the wrong reason
# demonstrates nothing. OUT_DIR defaults to a directory under the system
# temporary directory and is removed on exit unless it was passed in.
#
# Exits non-zero if a plant that is meant to be refused passes, if a plant is
# refused by a check other than the one it is named for, or if the acceptance
# run of any pass is refused.

set -u

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT" || exit 1

if [ $# -ge 1 ]; then
  OUT="$1"
  CLEAN=0
else
  OUT="$(mktemp -d)"
  CLEAN=1
fi
trap '[ "$CLEAN" = 1 ] && rm -rf "$OUT"' EXIT

PY="${PYTHON:-python3}"
STATUS=0

echo "== regenerating plants under $OUT =="
"$PY" tools/make-plants.py "$OUT/plants" | sed 's/^/   /'
echo

# The manifest is the generator's own record of which check each plant is
# supposed to trip. Reading it back rather than re-deriving the expectation here
# means the harness cannot drift from the generator: one source, two consumers.
expected_for() {
  "$PY" - "$OUT/plants/manifest.json" "$1" <<'PYEOF' 2>/dev/null || true
import json, sys
manifest = json.load(open(sys.argv[1], encoding="utf-8"))
name = sys.argv[2]
for plant in manifest["plants"]:
    if plant["name"] == name:
        print(" ".join(plant["expects"]))
        break
PYEOF
}

echo "== refusals: each plant must be caught by the check it is named for =="
for plant in "$OUT"/plants/*/; do
  name="$(basename "$plant")"
  wanted="$(expected_for "$name")"
  for pass_dir in "$plant"*/; do
    [ -d "$pass_dir" ] || continue
    out="$("$PY" tools/validate.py "$pass_dir" 2>&1)"
    code=$?
    tripped="$(grep -oP '(?<=- )\[[a-z-]+\]' <<<"$out" | sort -u | tr '\n' ' ')"
    if [ "$code" -eq 0 ]; then
      printf '   FAIL %-22s expected a refusal, the gate exited 0\n' "$name"
      STATUS=1
      continue
    fi
    if [ -z "$wanted" ]; then
      printf '   FAIL %-22s no expectation in manifest.json, so this refusal proves nothing\n' "$name"
      STATUS=1
      continue
    fi
    # The assertion this harness was missing: the plant must be caught by the
    # check it is named for, not merely by anything. A check that fires for the
    # wrong reason, or stops firing because its name changed, is a refusal that
    # proves nothing about the check it claims to demonstrate.
    missed=""
    for want in $wanted; do
      grep -q "\[$want\]" <<<"$tripped" || missed="$missed $want"
    done
    if [ -n "$missed" ]; then
      printf '   FAIL %-22s tripped but not by %s (got:%s)\n' "$name" "$missed" "$tripped"
      STATUS=1
      continue
    fi
    printf '   ok   %-22s exit=%s  tripped: %s\n' "$name" "$code" "$tripped"
  done
done
echo

echo "== acceptances: the corrected data must pass =="
for pass_dir in 2026-09-13 2026-09-20 2026-10-02 2026-10-06; do
  out="$("$PY" tools/validate.py "$pass_dir" 2>&1)"
  code=$?
  if [ "$code" -eq 0 ]; then
    printf '   ok   %-12s exit=0\n' "$pass_dir"
  else
    printf '   FAIL %-12s exit=%s\n%s\n' "$pass_dir" "$code" "$out"
    STATUS=1
  fi
done

echo
echo "== whole repository =="
out="$("$PY" tools/validate.py --all 2>&1)"
code=$?
if [ "$code" -eq 0 ]; then
  printf '   ok   validate.py --all exit=0\n'
else
  printf '   FAIL validate.py --all exit=%s\n%s\n' "$code" "$out"
  STATUS=1
fi

exit "$STATUS"