#!/usr/bin/env python3
"""Data-integrity gate for a coding-subs research pass.

    python3 tools/validate.py [PASS_DIR ...]   # default: newest YYYY-MM-DD dir
    python3 tools/validate.py --all            # every pass in the repo

Exit code 0 only when every check passes. Each check exists because a real,
named defect got past the previous validator; CHECKS in tools/gate/registry.py
is the registry, one entry per registered check, and `gate-count-claims` refuses
any count in the documentation that disagrees with it. The checks themselves
live in tools/gate/, one module per responsibility. The failing-before evidence
for every check is in docs/reviews-*.md, with the plant fixtures it was
demonstrated against generated by tools/make-plants.py and run by
tests/run-plants.sh.

Every check falls into one of four families.

**Shape.** A row must have the field count its header declares; a cell must hold
the kind of value its column name promises; a row count or a cited path in prose
must be what the files on disk say; a plan price, a monthly token count and a
cost per million on one row must describe one quantity in three units; a row's
token count must be the division it claims to have performed; a token figure's
magnitude must agree with its own column's unit and with what a monthly
allowance can physically be.

**Sourcing.** Every number must carry an evidence class from the closed
vocabulary the root README declares; every money figure quoted in a references
file must be present in the archived bytes of the page that entry cites; every
recorded SHA-256 must be the hash of the bytes actually archived; every archived
source must have a fetch log entry and every logged retrieval an archived file.

**Semantics.** A capability score must be traceable to a leaderboard row for
that exact SKU rather than inherited from a different one; a per-model dollar
ceiling must say whether it is independent or drawn against a shared pool; a
derived $/M or tokens/month figure must state the traffic mix it was computed
under; a provenance string must not assert a dated measurement that no fetch log
entry records.

**Self-description.** A document claiming a number of checks must state the
number the registry holds.

None of these can be verified by reading a report, which is why they are checks
rather than conventions.
"""
from __future__ import annotations

import sys
from pathlib import Path

if str(Path(__file__).resolve().parent) not in sys.path:
    sys.path.insert(0, str(Path(__file__).resolve().parent))

from gate.registry import CHECKS
from gate.runner import main, validate

__all__ = ["CHECKS", "main", "validate"]


if __name__ == "__main__":
    sys.exit(main())
